Event:
  fields:
    default: id, name, date, user, limit
    form: user, location, name, date, limit, description
  order_by: -created_at
  search: name, description
  actions:
    edit: publish
  application: CRUD
