Highlight:
  fields:
    default: id, description, start_at, end_at
    form: url, description, start_at, end_at
  order_by: -created_at
  search: description
  actions:
    edit: disable
  application: CRUD
